{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: public-gateway-ingress
      namespace: gateway
      sectionName: https
  hostnames:
    - {{ .Values.httpRoute.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "vllm.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
