{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc }}
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: 500Gi
{{- end }}
